version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
  signal:
    build: .
    ports:
      - 8001:8001
  panel:
    build: .
    ports:
      - 8000:8000
